gathertown/casper-3

- cmd/casper-3/main.go
- deployments/base/deployment.yaml
- internal/config/config.go
- internal/config/config_test.go
- pkg/kubernetes/nodes.go
- pkg/kubernetes/nodes_test.go
This PR enables the functionality of accepting multiple labelValues
To monitor multiple kubernetes nodes with different labels.
Tested locally:
```bash
➜  casper-3 git:(dev/achilleas-ENG-2191) ✗ make test
go test -v -coverpkg=./... -coverprofile=profile.cov ./...
?   	github.com/gathertown/casper-3/cmd/casper-3	[no test files]
=== RUN   TestFromEnv
config_test.go:24: Setting env "ENV"="development"
config_test.go:25: Setting env "INTERVAL"="61"
config_test.go:26: Setting env "PROVIDER"="digitalocean"
config_test.go:27: Setting env "LABEL_KEY"="doks.digitalocean.com/node-pool"
config_test.go:28: Setting env "LABEL_VALUES"="sfu"
config_test.go:29: Setting env "TOKEN"="abcd1231"
config_test.go:30: Setting env "SUBDOMAIN"="dev"
config_test.go:31: Setting env "ZONE"="k8s.gather.town"
--- PASS: …
```
> Dev/achilleas eng 2191 feat: Accept multiple labelValues

- pkg/kubernetes/nodes.go
- pkg/kubernetes/nodes_test.go
If IPv4 address is not found on a node, the application panics:
```
goroutine 1 [running]:
github.com/gathertown/casper-3/pkg/kubernetes.(*Cluster).Nodes(0xc0003f3d20, 0x0, 0x0, 0xc00021bed8, 0xa, 0xa)
/app/pkg/kubernetes/nodes.go:30 +0x2ae
main.main()
/app/cmd/casper-3/main.go:53 +0x4d5
```
This PR handles this situation gracefully. If the IPv4 address is not
found, we're not adding the node the list of existing nods in the
kubernetes cluster.
> feat: Handle lack of IPv4 address gracefully

- cmd/casper-3/main.go
- pkg/providers/cloudflare/dnsrecord.go
- pkg/providers/digitalocean/dnsrecord.go
Log errors instead of return them, to allow routine to proceed with cleanup in case a record creation failed.
> [fix]: log errors instead of return them on Sync() function, to allow routine completion

- cmd/casper-3/main.go
- internal/config/config.go
- pkg/kubernetes/nodes.go
- pkg/log/log.go
- pkg/log/log_test.go
- pkg/providers/cloudflare/dnsrecord.go
- pkg/providers/digitalocean/dnsrecord.go
We're using the environment flag in to generate the TXT records. Using
"development" environment in a production cluster will break
consistency, as the records will have a different flag.
Introducing the `LOGLEVEL` var to enable debug mode.
> refactor: decouple log level from environment

- cmd/casper-3/main.go
- deployments/base/clusterrole.yaml
- deployments/base/deployment.yaml
- internal/config/config.go
- pkg/common.go
- pkg/kubernetes/nodes.go
- pkg/kubernetes/nodes_test.go
- pkg/kubernetes/pods.go
- pkg/kubernetes/pods_test.go
- pkg/log/log.go
- pkg/log/log_test.go
- pkg/providers/cloudflare/dnsrecord.go
- pkg/providers/digitalocean/dnsrecord.go
This PR adds the functionality to casper-3 to monitor certain pod labels and create dns records based on their name.
This feature can be used from statefulsets that use the hostNetwork mode.
In that case, pods will be created with a name that follows this pattern: 
```
{sts-name}-{ordinal-index}
```
Since casper-3 already creates DNS records for k8s nodes, if we use hostNetwork mode, we could just use those DNS records. But that's not always convenient and can be dangerous.
There are cases, like routers, that all available endpoints need to be known from other applications.
If we consider the k8s node DNS record as the router record, that can lead to outage in case the k8s node change.
By adding the `casper-3.gather.town/sync: "true"` label on the statefulset, casper-3 will create and …
> [feat]: Monitor pod labels and create DNS records based on pod names

- pkg/providers/cloudflare/dnsrecord.go
We were trying to fetch txtRecords and compare their labels from the txtRecord.Data field, but txtLabels can be found from the Content field, instead of the Data. 
This PR fixes that bug.
> [fix]: get the textRecord Content instead of Data

- .circleci/config.yml
This PR removes the deployment jobs on the legacy clusters, since now they are deleted
> fix: Remove legacy clusters

- pkg/providers/digitalocean/dnsrecord.go
The `digitalocean` provider prints messages like:
```
2021-12-03 08:20:13 time="2021-12-03T06:20:13Z" level=info msg="Entries to be added" entries="[]"
```
on every run. There's no need to populate the logging system when
`entries` slice is empty.
> refactor: Don't print messages when not needed

- .circleci/config.yml
- deployments/base/casper-3-environment.yaml
- deployments/base/docker-registry.yaml
- deployments/base/kustomization.yaml
- deployments/overlays/cluster/deployment.yaml
- deployments/overlays/cluster/kustomization.yaml
Switch to Doppler for fetching the secrets. For that, we are making
use of the DopplerSecret CRD. We are also making use of the
DOCKERHUB_CREDENTIALS project variable to provision the docker-registry
kubernetes secret.
> feat: Switch to Doppler for secrets

- deployments/base/casper-3-environment.yaml
The namespace is always 'infrastructure' so lets drop the variable
since we never really replaced it.
> fix: Drop __KUSTOMIZE_NAMESPACE__ variable

- .circleci/config.yml
We switched to CloudFlare for the development environment. Switching
`casper-3` to use CloudFlare for the development environment.
> Switch the `dev` environment to cloudflare provider

- cmd/casper-3/main.go
If we encounter an error when talking to Kubernetes API we need to terminate
the current iteration instead of proceeding with (possibly?) and empty
slice of hosts as that would result in actually removing all entries for
them.
> main: Prevent execution when there are errors talking to API

- pkg/common.go
- pkg/common_test.go
- pkg/providers/cloudflare/dnsrecord.go
- pkg/providers/digitalocean/dnsrecord.go
feat:Compare record & node prefixes before deletion
This commit introduces a common function `RecordPrefixMatchesNodePrefixes`
that aims to check if there is a match between record and node
prefixes. Casper-3 should be allowed to delete only records that
are prefixed with the labeled k8s node prefixes too. Let's add this
check as a safeguard here, in order to avoid the deletion of unwilling
records.
> feat: Compare record & node prefixes before deletion

- .circleci/config.yml
- deployments/overlays/cluster/deployment.yaml
- internal/config/config.go
- pkg/providers/cloudflare/dnsrecord.go
Add ability to create proxied cloudflare records. This is being
controlled by the CLOUDFLARE_PROXIED env variable and it's turn on
by default on development environment.
> feat: Add ability to create proxied cloudflare records

- deployments/overlays/cluster/deployment.yaml
- pkg/providers/cloudflare/dnsrecord.go
We are seeing the following problem during deployment
```
cannot convert int64 to string
```
Apparently boolean in circleci is being passed as '1' or '0' so
lets add the missing quotes.
Finally, fix the logging of proxied records as it was previously done
on the TXT type instead of the A one.
> Add missing quotes for boolean values

- .circleci/config.yml
- deployments/base/deployment.yaml
- deployments/overlays/cluster/deployment.yaml
- internal/config/config.go
- internal/config/config_test.go
This PR adds support for gameserver nodes in `casper-3`. We already had support for handling multiple node labels while building `labelSelector` in `GetNodes`. The only thing left was to make sure that `LabelValues` env variable is properly formatted for use as a [set based label requirement](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement)
> feat: add casper 3 support for gs

- .circleci/config.yml
We are hitting https://github.com/CircleCI-Public/aws-eks-orb/issues/67
so lets hardcode the version of kubectl that we install to match
the one that we have in our k8s clusters.
> [circleci] Force kubectl 1.21

- .circleci/config.yml
The doks orb has the tendency to install too many unecessary tools like
kubectl and kops. We do not really need that as we installing kubectl
through the official orb and we also do not need kops. As such lets
switch to doctl orb instead which only installs the doctl tool.
> [circleci] Switch to doctl orb

- .circleci/config.yml
The AWS PoC cluster is going to be cleaned up. Removing casper-3 deployment instructions to avoid CI errors.
> feat: Remove AWS deployment support

- .circleci/config.yml
The TOKEN env variable is being populated by the Doppler operator so
remove references to it from the deployment configuration to avoid
confusion.
> chore: Remove token circleci parameter

- deployments/base/deployment.yaml
Adjust casper-3 limits and requests to make space for other pods, in this case falco-IDS. Although we do not define `requests`, kubernetes will use the `limits` to set `requests` as well.
Casper-3 uses very low vCPU (max is 75m according to Prometheus in sgp-1b) and memory rarely goes above 32MB.
Use these as requests and keep the limits close as we don't see spikes in a 14d span.
> feat: Adjust casper-3 limits

- .circleci/config.yml
We do not have an edge certificate for the GKE POC cluster so proxying
that through cloudflare results to certificate problems. Lets drop it.
> [INFRA-529]chore: Drop Cloudflare proxy for GKE records

- .circleci/config.yml
The GKE cluster will go away so lets remove the deployment from the CD
> chore: Remove GKE deployment
